#undef PRISM_COUNT_ARGS_IMPL
#undef PRISM_COUNT_ARGS

#undef PRISM_CONCAT
#undef PRISM_CONCAT_IMPL

#undef PRISM_REMOVE_PARENS

#undef PRISM_FOR_EACH

#undef PRISM_SEPARATOR

#undef PRISM_FOR_EACH_IMPL_1
#undef PRISM_FOR_EACH_IMPL_2
#undef PRISM_FOR_EACH_IMPL_3
#undef PRISM_FOR_EACH_IMPL_4
#undef PRISM_FOR_EACH_IMPL_5
#undef PRISM_FOR_EACH_IMPL_6
#undef PRISM_FOR_EACH_IMPL_7
#undef PRISM_FOR_EACH_IMPL_8
#undef PRISM_FOR_EACH_IMPL_9
#undef PRISM_FOR_EACH_IMPL_10
